"""
Purpose: Generate a tiny but valid PDF so the demo invoices can be downloaded and opened.
Input/Output: Receives short text lines and returns PDF bytes.
Invariants: The returned bytes always start with a PDF header and include exactly one page.
Debug: If a downloaded invoice does not open, inspect the generated bytes and confirm the xref offsets.
"""

from __future__ import annotations

from typing import Iterable


def _escape_pdf_text(value: str) -> str:
    return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def generate_demo_invoice_pdf(text_lines: Iterable[str]) -> bytes:
    """Build a compact one-page PDF without external dependencies."""

    lines = list(text_lines) or ["Tesla Invoice Demo"]
    text_commands: list[str] = []
    y_position = 740

    # Each line is placed separately so invoice metadata stays readable in common PDF viewers.
    for line in lines:
        escaped_line = _escape_pdf_text(line)
        text_commands.append(f"BT /F1 12 Tf 60 {y_position} Td ({escaped_line}) Tj ET")
        y_position -= 24

    content_stream = "\n".join(text_commands).encode("latin-1")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
            b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>"
        ),
        b"<< /Length %d >>\nstream\n%s\nendstream" % (len(content_stream), content_stream),
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    pdf_parts: list[bytes] = [b"%PDF-1.4\n"]
    offsets: list[int] = []

    for index, object_body in enumerate(objects, start=1):
        offsets.append(sum(len(part) for part in pdf_parts))
        pdf_parts.append(f"{index} 0 obj\n".encode("ascii"))
        pdf_parts.append(object_body)
        pdf_parts.append(b"\nendobj\n")

    xref_offset = sum(len(part) for part in pdf_parts)
    pdf_parts.append(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    pdf_parts.append(b"0000000000 65535 f \n")

    for offset in offsets:
        pdf_parts.append(f"{offset:010d} 00000 n \n".encode("ascii"))

    pdf_parts.append(
        (
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref_offset}\n%%EOF\n"
        ).encode("ascii")
    )
    return b"".join(pdf_parts)

